default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: clone1_development
test:
  <<: *default
  database: clone1_test
production:
  <<: *default
  database: clone1_production
  username: clone1
  password: <%= ENV['CLONE1_DATABASE_PASSWORD'] %>
